// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9HcTcnDcjqIcN2UAY2izxKY_MrTxiyJI',
    appId: '1:561781217644:web:7f28237f99b499fe527b49',
    messagingSenderId: '561781217644',
    projectId: 'taski2-52abc',
    authDomain: 'taski2-52abc.firebaseapp.com',
    storageBucket: 'taski2-52abc.firebasestorage.app',
    measurementId: 'G-J96S1SRML7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3lGFXiHhFB7ISrjmzOiPzasZh8eSbW8o',
    appId: '1:561781217644:android:63a282f590db277f527b49',
    messagingSenderId: '561781217644',
    projectId: 'taski2-52abc',
    storageBucket: 'taski2-52abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoWAtCbQQjihF2M7OQXMEzaX_Jgn1W_k',
    appId: '1:561781217644:ios:23319a7f82ee63a3527b49',
    messagingSenderId: '561781217644',
    projectId: 'taski2-52abc',
    storageBucket: 'taski2-52abc.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIoWAtCbQQjihF2M7OQXMEzaX_Jgn1W_k',
    appId: '1:561781217644:ios:23319a7f82ee63a3527b49',
    messagingSenderId: '561781217644',
    projectId: 'taski2-52abc',
    storageBucket: 'taski2-52abc.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9HcTcnDcjqIcN2UAY2izxKY_MrTxiyJI',
    appId: '1:561781217644:web:8d93afecdf91d02d527b49',
    messagingSenderId: '561781217644',
    projectId: 'taski2-52abc',
    authDomain: 'taski2-52abc.firebaseapp.com',
    storageBucket: 'taski2-52abc.firebasestorage.app',
    measurementId: 'G-0N8LSWCX7M',
  );

}